name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Get Diff Action
      uses: technote-space/get-diff-action@v4.0.1
      with: 
        PATTERNS: | 
          +(scripts|resources)/**/*.py
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
      if: env.GIT_DIFF
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r $(git ls-files 'requirements.txt')
      if: env.GIT_DIFF
    - name: Check for syntax errors with pylin
      run: |
        pylint --errors-only $(git ls-files --directory scripts | grep -e ".py")
      if: env.GIT_DIFF
    - name: Analysing the code with pylint
      run: |
        pylint ${{ env.GIT_DIFF_FILTERED }}
      if: env.GIT_DIFF